# Generated by Django 5.1.4 on 2025-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0005_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
