# Generated by Django 5.1.4 on 2025-01-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0006_uploadedfile_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='is_valid',
            new_name='is_processed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_uploaded_files',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_valid', models.BooleanField(null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='otp_app.uploadedfile')),
            ],
        ),
    ]
