# Generated by Django 5.1.4 on 2025-01-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0009_rename_is_valid_uploadedfile_is_processed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='is_processed',
            new_name='is_valid',
        ),
    ]
