# Generated by Django 5.1.4 on 2025-01-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0010_rename_is_processed_uploadedfile_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='processed_file_url',
        ),
    ]
