# Generated by Django 5.1.4 on 2025-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0012_plan_userplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_views',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
