# Generated by Django 5.1.4 on 2025-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0013_remove_plan_max_views_plan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
