# Generated by Django 5.1.4 on 2025-01-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0014_plan_max_views'),
    ]

    operations = [
    ]
