# Generated by Django 5.1.4 on 2025-01-16 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0015_auto_20250116_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_views',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
