# Generated by Django 5.1.4 on 2025-01-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0016_remove_plan_max_views_alter_userplan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='total_views',
            new_name='remaining_credits',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AlterField(
            model_name='plan',
            name='credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otp_app.plan'),
        ),
    ]
