# Generated by Django 5.1.4 on 2025-01-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0017_rename_total_views_userplan_remaining_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
