# Generated by Django 5.1.4 on 2025-01-16 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0019_plan_planrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='requested_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otp_app.plan'),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
