# Generated by Django 5.1.4 on 2025-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0020_planrequest_requested_credits_alter_plan_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=50),
        ),
    ]
