# Generated by Django 5.1.4 on 2025-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0022_coupon_emailrecord_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='billing_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
