# Generated by Django 5.1.4 on 2025-02-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0024_billingdetail_delete_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='otp_app.coupon'),
        ),
    ]
