# Generated by Django 5.1.4 on 2025-02-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0026_planrequest_custom_price_planrequest_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
